ayasofyazilim-clomerce/unirefund-web

apps/web/src/utils/navbar/project-navbar-items.json

chore(navbar): add refund

---

apps/web/src/app/[lang]/(core)/home/page.tsx

chore: remove core/home

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/page.tsx

fix: contract redirect if partyName is not proper

---

apps/web/src/utils/navbar/project-navbar-items.json

fix(navbar): missing elements

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/rebate-settings/_components/rebate-settings.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/_components/contract-header-form/merchant/index.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/_components/contract-widgets.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate/rebate-form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate/table.tsx

refactor(Contract/Rebate): update forms and types due saas

---

apps/web/.eslintrc.js
apps/web/src/app/[lang]/(main)/error.tsx

chore(eslint): disable explicit-function-return-type rule

---

apps/web/auth-action.ts
apps/web/auth.ts
apps/web/src/app/[lang]/(main)/layout.tsx
packages/ui/src/providers/theme.tsx
packages/ui/src/theme/main-admin-layout/components/logo.tsx
packages/ui/src/theme/main-admin-layout/components/navbar.tsx
packages/ui/src/theme/main-admin-layout/header-section.tsx
packages/ui/src/theme/main-admin-layout/index.tsx

feat(tenant): show tenant information next to logo

---

apps/web/src/actions/unirefund/FinanceService/actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/vat-statements-table-data.tsx

refactor(vat statements): enhance the table of page

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/refunds/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refunds/refunds-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refunds/table.tsx
apps/web/src/language-data/core/Default/resources/tr.json
apps/web/src/language-data/unirefund/TagService/resources/en.json
apps/web/src/language-data/unirefund/TagService/resources/tr.json

chore: translate to refunds look this after #27

---

apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/[vatStatementId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/[vatStatementId]/tax-free-tags/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/[vatStatementId]/tax-free-tags/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/[vatStatementId]/tax-free-tags/tax-free-tag-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/vat-statements-table-data.tsx
apps/web/src/language-data/unirefund/FinanceService/resources/en.json
apps/web/src/language-data/unirefund/FinanceService/resources/tr.json

feat(vatStatement): add the Tax Free Tag section's table 

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/_components/merchant/index.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/_components/refund-point/index.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/_components/contract-header-form/merchant/index.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/_components/contract-header-form/refund-point/index.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/new/page.tsx

feat(Contract): validFrom dates disable control as possible

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/refunds/refunds-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/tax-free-tags-table-data.tsx
apps/web/src/language-data/unirefund/TagService/resources/en.json
apps/web/src/language-data/unirefund/TagService/resources/tr.json

chore(tax-free-tags): add date filters

---

apps/web/src/app/[lang]/(auth)/[auth]/page.tsx

feat: auth app logo

---

packages/ui/src/form-ready/index.tsx

feat:formReadyComponent

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/new/page.tsx
apps/web/src/language-data/unirefund/CRMService/resources/en.json
apps/web/src/language-data/unirefund/CRMService/resources/tr.json

closes [#893](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/893)

feat: check tax-office before create party

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/table.tsx

#closes [#1037](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1037)

fix: tag table scroll visiblity

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/refund-form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/table.tsx

style(tag)

---

apps/web/package.json
apps/web/src/actions/core/IdentityService/actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/individuals-table/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/page.tsx
packages/ui/package.json
pnpm-lock.yaml

chore(identity service): saas update

---

packages/ui/src/action-button/index.tsx

feat:ActionList & ActionButton component

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/affiliations/affiliations-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/affiliations/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/page.tsx

feat(parties): add affiliations table

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/_components/merchant/index.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/_components/refund-point/index.tsx

feat(ContractHeader): use ui component for actions

---

apps/web/src/actions/unirefund/ContractService/delete-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/[id]/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/[id]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/[id]/form.tsx

closes [#1044](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1044)

feat: delete actions for refundFees & refundTables

---

CLEANCODE.md

docs: cleancode structure samples

---

apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/page.tsx

refactor(Vat Statements): filter the merchants to show only headquarters of merchants

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/affiliations/[partyType]/_components/affiliations-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/affiliations/[partyType]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/affiliations/[partyType]/_components/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/affiliations/[partyType]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/affiliations/[partyType]/page.tsx

feat: add affilation page

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/product/product-groups/_components/product-groups-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/product/product-groups/_components/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/product/product-groups/page.tsx

refactor(Product groups): use tanstack table

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/product/product-groups/[productGroupId]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/product/product-groups/[productGroupId]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/product/product-groups/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/product/product-groups/new/page.tsx

feat(Product group): add create & edit forms

---

packages/ui/src/theme/main-admin-layout/components/navbar.tsx

chore(navbar): remove the section that was under main list

---

apps/web/src/utils/navbar/project-navbar-items.json

user with tenant
admin without tenant

chore(permission): add permssion to pages in core list

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/_components/table/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/_components/table/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/_components/traveller-document-form.tsx

feat(refund): add refund table component and related data handling

---

apps/web/src/utils/navbar/project-navbar-items.json

feat: add Refunds management item to the operations navbar

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/[refundType]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refunds/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/stores/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/page.tsx

feat: add error handling to pages

---

apps/web/src/actions/unirefund/CrmService/search.ts
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/_components/filter.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/_components/tax-free-tags-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/page.tsx

refactor(tax-free-tags): add left filter section

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/[refundType]/client-page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/[refundType]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/_components/table/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/_components/filter.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/page.tsx
apps/web/src/utils/utils-date.ts

style(tax-free-tags): small changes

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/tag-actions.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/page.tsx
apps/web/src/language-data/unirefund/TagService/resources/en.json
apps/web/src/language-data/unirefund/TagService/resources/tr.json

feat: add TagActions component for managing tag actions in tax-free tags 

---

apps/web/package.json
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract-settings/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/rebate-settings/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/identification/[identificationId]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/page.tsx
packages/ui/package.json
pnpm-lock.yaml

feat(parties): implement error handling with ErrorComponent & crm saas update

---

apps/web/src/actions/unirefund/CrmService/actions.ts
apps/web/src/actions/unirefund/CrmService/types.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/action.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/address/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/email/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/individuals-table/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/organization/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/subcompanies-table/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/telephone/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/utils.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/action.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/new/crm/organization/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/new/page-client.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/types.ts
apps/web/src/app/[lang]/(main)/(unirefund)/settings/affiliations/[partyType]/page.tsx

refactor: update PartyNameType import paths across multiple files

---

apps/web/package.json
apps/web/src/app/[lang]/(main)/(unirefund)/operations/filter.ts
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/[refundType]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/_components/table/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/tag-actions.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/_components/filter.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/page.tsx
packages/ui/package.json
pnpm-lock.yaml

fix: update refund operations to use consistent parameter names & saas update

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/[refundType]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/_components/table/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/tag-actions.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/tag-summary.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/totals.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/page.tsx

fix(refund): improve parameter handling in redirect logic

---

apps/web/src/types.ts

chore:merge commit core

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/product/product-groups/[productGroupId]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/product/vats/[vatId]/_components/form.tsx

chore(product): change the post function to put function

---

apps/web/src/actions/unirefund/CrmService/detele-actions.ts
apps/web/src/actions/unirefund/CrmService/put-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/settings/affiliations/[partyType]/_components/affiliations-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/affiliations/[partyType]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/affiliations/[partyType]/_components/table.tsx

closes [#1109](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1109)

feat: implement delete and update API actions for affiliation codes

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/purchase-details/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/tag-tabs.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/page.tsx
apps/web/src/language-data/unirefund/TagService/resources/en.json
apps/web/src/language-data/unirefund/TagService/resources/tr.json
packages/ui/package.json
pnpm-lock.yaml

feat((tax-free-tag-detail)): show product groups in tag detail

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/export-validations/[exportValidationId]/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/export-validations/[exportValidationId]/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/tag-actions.tsx

…ortValidationid to render the id of tag

refactor(export validation): remove tag and tagid folders and use exportValidationid to render the id of tag

---

apps/web/package.json
apps/web/src/actions/unirefund/FinanceService/post-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/new/page.tsx
packages/ui/package.json
pnpm-lock.yaml

fix(finance): update API function names and dependencies for VAT 

---

apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/new/page.tsx

feat(vat-statements): add error handling component for merchant list

---

apps/web/src/app/[lang]/(main)/(unirefund)/finance/rebate-statements/_components/rebate-statements-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/rebate-statements/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/rebate-statements/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/_components/vat-statements-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/new/_components/form.tsx
apps/web/src/language-data/unirefund/FinanceService/resources/en.json
apps/web/src/language-data/unirefund/FinanceService/resources/tr.json

refactor(finance): add create form of rebate statement and enhance the codes

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/product/product-groups/_components/product-groups-table-data.tsx
pnpm-lock.yaml

chore: disappear the vatId and show the vat Percent

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/_components/contract-header-form/merchant/index.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/new/page.tsx

fix: make fromDate optional in contract header form components

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/_components/merchant/index.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/_components/refund-point/index.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/_components/contract-header-form/refund-point/index.tsx

fix: make fromDate optional in contract components

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/_components/contract-header-form/merchant/index.tsx

closes [#1152](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1152)

feat: add edit link for selected refund table header in contract form

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/_components/product-groups/product-group-table-data.tsx

chore: show the vatPercent instead of vatId in productGroup in merchant

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/rebate-settings/_components/rebate-settings.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/rebate-settings/page.tsx

closes [#1160](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1160)

feat: add individuals support in rebate settings

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/_components/merchant/index.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/_components/refund-point/index.tsx

chore: comment out unused ActionButton components in contract actions

---

publish-cli.sh
turbo.json

chore: updatecore

---

apps/web/src/lib.ts

fix: change the import of session

---

.github/workflows/lint-main.yml
.github/workflows/lint-pull-requests.yml

refactor: update linting workflows for consistency and clarity

---

publish-cli.sh

chore:update core 

---

packages/ui/src/theme/main-admin-layout/header-section.tsx

Update PageHeader import to use dynamic loading

---

packages/ui/src/theme/main-admin-layout/header-section.tsx

Add loading skeleton for dynamic PageHeader component

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/_components/individuals-table/individuals-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/_components/individuals-table/table.tsx
apps/web/src/language-data/unirefund/CRMService/resources/en.json
apps/web/src/language-data/unirefund/CRMService/resources/tr.json

refactor(Merchant/individual): use schema form instead of autoform

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/_components/individuals-table/individuals-table-data.tsx

feat(merchant/individual): add affilation role code to action list

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/page.tsx

style(tax-free-tags): add overflow auto

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/totals-earnings.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/page.tsx
apps/web/src/language-data/unirefund/TagService/resources/en.json
apps/web/src/language-data/unirefund/TagService/resources/tr.json

feat(tax-free-tags): add tag earnings & totals section to tag detail

---

apps/web/src/actions/core/AccountService/actions.ts
apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/[roleId]/permissions/_components/permissions.tsx
apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/permissions/_components/permissions.tsx
apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/[applicationId]/life-token/page.tsx
apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/[applicationId]/permissions/_components/permissions.tsx
apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/[applicationId]/permissions/page.tsx
apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/new/page.tsx

merge core into unirefund

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[merchantId]/detail/info/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[merchantId]/detail/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[merchantId]/detail/organization/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[merchantId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[merchantId]/sub-stores/page.tsx

feat(merchant-layout): add new layout component for merchant details

---

apps/web/src/actions/api-requests.ts
apps/web/src/actions/unirefund/ContractService/put-actions.ts

refactor(api-requests): remove unused contract header API methods 

---

apps/web/package.json
apps/web/src/actions/unirefund/CrmService/actions.ts
apps/web/src/actions/unirefund/CrmService/put-actions.ts
apps/web/src/actions/unirefund/LocationService/actions.ts
apps/web/src/actions/unirefund/LocationService/use-address-hook.tsx.tsx
apps/web/src/actions/unirefund/LocationService/utils.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/address/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/address/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/email/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/email/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/phone/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/phone/page.tsx
packages/ui/package.json
pnpm-lock.yaml

feat(parties/merchant/address): add edit address page & solve address fields empty bug

---

apps/web/src/actions/unirefund/CrmService/actions.ts
apps/web/src/actions/unirefund/CrmService/put-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/info/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/address/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/address/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/layout.tsx

refactor(parties/refund-points): add API integration and UI for managing refund point addresses

---

apps/web/src/actions/unirefund/CrmService/actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/sub-stores/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/sub-stores/sub-store-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/sub-stores/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/page.tsx

refactor(parties/merchants/sub-stores): implement sub-stores table & better api handling in general

---

apps/web/src/actions/unirefund/CrmService/actions.ts
apps/web/src/actions/unirefund/CrmService/search.ts
apps/web/src/actions/unirefund/LocationService/actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/finance/rebate-statements/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/address/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/email/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/info/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/phone/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/sub-stores/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/address/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/sub-stores/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/sub-stores/sub-store-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/sub-stores/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/page.tsx

refactor(parties/refund-points): add sub-stores page

---

apps/web/package.json
apps/web/src/actions/unirefund/CrmService/put-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/action.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/info/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/info/page.tsx
packages/ui/package.json
pnpm-lock.yaml

refactor(crm): update saas & add refund point base update

---

apps/web/src/actions/unirefund/CrmService/actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/affiliations/affiliations-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/affiliations/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/affiliations/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/sub-stores/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/sub-stores/sub-store-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/sub-stores/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/affiliations/affiliations-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/affiliations/affiliations-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/affiliations/affiliations-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/affiliations/affiliations-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/affiliations/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/affiliations/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/sub-stores/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/sub-stores/sub-store-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/sub-stores/table.tsx
pnpm-lock.yaml

feat(parties): add isAbpUser to Affilations table & add tax office affilations & add tax office sub stores & update ui

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/_components/merchant/index.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/_components/refund-point/index.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/_components/contract-header-form/merchant/index.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/_components/contract-header-form/refund-point/index.tsx
pnpm-lock.yaml

feat(Contract): refactor RefundFee/RefundTable headers handling

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/layout.tsx

feat(parties/layouts): disable "Details" tab in various party layouts

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/rebate-settings/_components/rebate-settings.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/rebate-settings/page.tsx

refactor: rebate settings contract tables

---

apps/web/package.json
packages/ui/package.json
pnpm-lock.yaml

chore: update @ayasofyazilim/saas dependency to version 0.0.124

---

apps/web/src/actions/unirefund/CrmService/actions.ts
apps/web/src/actions/unirefund/CrmService/put-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/sub-stores/sub-store-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/sub-stores/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/product-groups/product-group-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/product-groups/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/sub-stores/sub-store-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/sub-stores/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/email/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/email/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/sub-stores/sub-store-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/sub-stores/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/sub-stores/sub-store-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/sub-stores/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/sub-stores/sub-store-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/sub-stores/table.tsx

feat(parties): add product group links & add email put to refund point & fix new sub store link & fix party detail link

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/new/_components/individual/data.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/new/_components/individual/form.tsx

refactor(merchant): add create merchant individual form

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/new/_components/data.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/new/page.tsx

refactor(customs): add create custom organization form

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/new/_components/data.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/new/page.tsx

refactor(taxoffice): add create taxoffice organization form

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/new/_components/data.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/new/page.tsx

refactor(refondPoints): add create refondPoints organization form

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/new/_components/data.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/new/page.tsx

refactor(taxfree): add create taxfree organization form

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/new/_components/data.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/new/page.tsx

refactor(individual): add create individual form

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/new/layout.tsx

fix(rebate-tables): update router path for creating new rebate table

---

apps/web/src/actions/unirefund/CrmService/actions.ts
apps/web/src/actions/unirefund/CrmService/put-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/details/info/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/details/organization/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/address/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/email/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/info/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/organization/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/phone/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/address/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/email/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/info/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/organization/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/phone/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/details/info/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/details/organization/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/details/email/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/details/email/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/details/info/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/details/organization/form.tsx

feat(tax-offices): add email management for tax offices with API inte… & add loading

---

apps/web/src/actions/unirefund/CrmService/delete-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/affiliations/affiliations-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/affiliations/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/affiliations/table.tsx

feat(customs): add delete customs affilation & add permissions

---

apps/web/src/actions/unirefund/ContractService/action.ts
apps/web/src/actions/unirefund/CrmService/actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/[contractId]/contract/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/[partyName]/[partyId]/contracts/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/_components/contact-header-form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/_components/contract-widgets.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/contracts/_components/contract-header-form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/contracts/new/page.tsx

feat(parties/contracts/new): add merchant & refund point contract creation page and associated widgets

---

apps/web/package.json
apps/web/src/actions/unirefund/CrmService/actions.ts
apps/web/src/actions/unirefund/CrmService/put-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/details/email/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/details/email/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/details/layout.tsx
packages/ui/package.json
pnpm-lock.yaml

feat(parties/customs): add email & update saas

---

apps/web/src/actions/unirefund/CrmService/actions.ts
apps/web/src/actions/unirefund/CrmService/put-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/details/address/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/details/address/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/details/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/details/phone/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/details/phone/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/details/address/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/details/address/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/details/email/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/details/email/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/details/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/details/phone/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/details/phone/page.tsx

feat(parties/[customs&tax-free]): add telephone & add adrdess & add email

---

apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(core)/management/identity/users/new/_components/form.tsx
apps/web/src/language-data/core/AbpUiNavigation/resources/en.json
apps/web/src/language-data/core/AbpUiNavigation/resources/tr.json

chore(core): merge core to unirefund

---

apps/web/src/actions/unirefund/CrmService/actions.ts
apps/web/src/actions/unirefund/CrmService/delete-actions.ts
apps/web/src/actions/unirefund/CrmService/put-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/individuals-table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/table.tsx

refactor(individual): use new system for get the data from backend

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/layout.tsx

feat(traveller): add header to edit page

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/export-validations/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refunds/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/details/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/new/_components/individual/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/new/_components/organization/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/details/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/details/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/new/form.tsx

chore(small changes): 

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/[partyId]/details/address/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/[partyId]/details/email/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/[partyId]/details/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/[partyId]/details/name/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/[partyId]/details/personal-summary/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/[partyId]/details/phone/page.tsx

feat(individual): add permssions

---

apps/web/src/actions/unirefund/ContractService/post-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/contracts/[contractId]/contract/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/contracts/new/_components/form.tsx

feat(RefundPointContract): update api calls

---

apps/web/src/actions/core/AccountService/actions.ts
apps/web/src/app/[lang]/(auth)/[auth]/client.tsx

feat: add tenantId support in signUpServer and AuthPage validation

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/new/components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/product-groups/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/contracts/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/contracts/new/page.tsx
apps/web/src/language-data/unirefund/CRMService/resources/en.json
apps/web/src/language-data/unirefund/CRMService/resources/tr.json
apps/web/src/language-data/unirefund/ContractService/resources/en.json
apps/web/src/language-data/unirefund/ContractService/resources/tr.json
packages/utils/api/action.ts
packages/utils/api/client-utils.ts

feat(FormReady): Merchant & RefundPoint missing field controls

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/[id]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/_components/refund-table-details-field.tsx

fix(RefundTables): refundTableDetails was missing in edit

---

apps/web/package.json
apps/web/src/app/[lang]/(main)/(unirefund)/settings/product/product-groups/[productGroupId]/_components/form.tsx
pnpm-lock.yaml

chore(settings): update saas to 130 version

---

apps/web/src/actions/unirefund/ContractService/action.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/[contractId]/contract-settings/_components/contract-settings.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/[contractId]/contract-settings/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/[contractId]/contract/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/[contractId]/rebate-settings/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/[contractId]/stores/page.tsx
apps/web/src/language-data/unirefund/ContractService/resources/en.json
apps/web/src/language-data/unirefund/ContractService/resources/tr.json

fix(ContractMerchant): formData was not provided in edit

---

apps/web/package.json
apps/web/src/app/[lang]/(main)/(unirefund)/operations/export-validations/[exportValidationId]/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/export-validations/_components/export-validations-table-data.tsx
apps/web/src/language-data/unirefund/ExportValidationService/resources/en.json
apps/web/src/language-data/unirefund/ExportValidationService/resources/tr.json
pnpm-lock.yaml

chore(tag): update saas to 131 version

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/tag-actions.tsx

fix: correct URL path for refund validation in tag actions component

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/export-validations/[exportValidationId]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/export-validations/[exportValidationId]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/export-validations/_components/export-validations-table-data.tsx
apps/web/src/language-data/unirefund/ExportValidationService/resources/en.json
apps/web/src/language-data/unirefund/ExportValidationService/resources/tr.json

…to tag number & remove delete button

chore(export Validation): change the field of edit from reference id to tag number & remove delete button

---

apps/web/src/app/[lang]/(main)/(core)/account/layout.tsx
apps/web/src/app/[lang]/(main)/(core)/account/personal-information/page.tsx
apps/web/src/app/[lang]/(main)/(core)/management/identity/organization/page.tsx
apps/web/src/app/[lang]/(main)/(core)/settings/tenant/[group]/group.tsx
apps/web/src/app/[lang]/(main)/(core)/settings/tenant/[group]/page.tsx
apps/web/src/utils/page-policy/page-policy.tsx

chore: merge core into unirefund

---

apps/web/src/app/[lang]/(main)/(core)/account/layout.tsx
apps/web/src/app/[lang]/(main)/(core)/management/identity/organization/page.tsx
packages/ui/src/theme/main-admin-layout/components/breadcrumb/index.tsx

refactor(breadcrumb): show child nav items in sub nav item

---

apps/web/src/actions/unirefund/FinanceService/actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/finance/rebate-statements/[rebateStatementId]/information/_components/rebate-statement-information.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/rebate-statements/[rebateStatementId]/information/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/rebate-statements/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/rebate-statements/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/rebate-statements/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/[vatStatementId]/information/_components/vat-statement-information.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/[vatStatementId]/information/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/[vatStatementId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/[vatStatementId]/tax-free-tags/_components/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/[vatStatementId]/tax-free-tags/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/page.tsx
apps/web/src/language-data/unirefund/FinanceService/resources/en.json
apps/web/src/language-data/unirefund/FinanceService/resources/tr.json

refactor(vat & rebate statements): fix the preview section in form & use the new system for getting data from backend

---

apps/web/src/actions/unirefund/ContractService/action.ts
apps/web/src/actions/unirefund/ContractService/delete-actions.ts
apps/web/src/actions/unirefund/ContractService/post-actions.ts
apps/web/src/actions/unirefund/ContractService/put-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/[contractId]/contract-settings/_components/contract-settings.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/[id]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/[id]/page.tsx

feat(contract-service): refactor API actions for merchant contract settings and improve error handling

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/page.tsx

feat(tax-free-tags): update sorting to include status in tag data

---

apps/web/src/actions/unirefund/ContractService/action.ts
apps/web/src/actions/unirefund/ContractService/post-actions.ts
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/_components/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/_components/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/_components/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/page.tsx

feat(Templates): clone from existing tables

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/new/_components/form.tsx

feat(TemplateTables): formData handling

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/_components/processing-fee-details.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/_components/rebate-table-details-field.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/_components/refund-fee-details-field.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/_components/refund-table-details-field.tsx

feat(tables): add row actions for moving up, moving down, and duplicating rows

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/_components/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/_components/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/_components/table.tsx

closes [#1250](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1250)

feat(tables): add merchant and refund point links to table headers

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/product-groups/product-group-table-data.tsx

feat(merchants/productGrooups): add condition to hide the action of defult product group

---

apps/web/src/app/[lang]/(main)/(unirefund)/finance/rebate-statements/[rebateStatementId]/information/_components/rebate-statement-information.tsx

chore(rebate): fix scroll

---

apps/web/src/app/[lang]/(auth)/layout.tsx

feat: add logo component to the authentication layout

---

apps/web/package.json
apps/web/src/app/[lang]/(auth)/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/page.tsx
packages/ui/package.json
packages/ui/utils/table/form-schemas.ts
pnpm-lock.yaml

fix(parties/new): unknown typeCode error

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/_components/table/form.tsx

chore(refunds): pass router to handlePostResponse in RefundForm component

---

packages/ui/src/theme/main-admin-layout/components/breadcrumb/index.tsx

fix: correct link key in BreadcrumbDropdown component

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/personal-identifications/[identificationId]/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/personal-identifications/new/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/personal-identifications/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/personal-preferences/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/personal-summary/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/new/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/new/page.tsx
apps/web/src/language-data/unirefund/TravellerService/resources/en.json
apps/web/src/language-data/unirefund/TravellerService/resources/tr.json
apps/web/src/utils/navbar/project-navbar-items.json

refactor(Traveller): enhance traveller forms with error handling and API integration

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/tag-card.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/page.tsx

closes [#1263](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1263)

style(tax-free-tags): make tag detail page responsive

---

apps/web/src/utils/navbar/project-navbar-items.json

chore(main list): add missing option

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/_components/utils.ts
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/page.tsx

feat: export tax-free tags utils and filter component

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/_components/filter.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/page.tsx

feat: enhance Filter component with className and defaultOpen props 

---

readme/SERVER_SIDE_README.md

docs(server-side): update readme

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/[id]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/_components/rebate-table-details-field.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/[id]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/[id]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/new/_components/form.tsx
apps/web/src/language-data/unirefund/ContractService/resources/en.json
apps/web/src/language-data/unirefund/ContractService/resources/tr.json

refactor: update language data for CloneForm in rebate and refund tables

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/new/_components/form.tsx
packages/ui/utils/table/form-schemas.ts

[#1273](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1273)

chore(individual): remove email type & use usetransitions & force create abp user

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/[partyId]/_components/individual-action-list.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/[partyId]/details/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/individuals-table-data.tsx
apps/web/src/utils/navbar/core-navbar-items.json
apps/web/src/utils/navbar/project-navbar-items.json
packages/ui/src/theme/main-admin-layout/components/breadcrumb/index.tsx
packages/ui/src/theme/main-admin-layout/components/navbar.tsx
packages/ui/src/theme/main-admin-layout/header-section.tsx

…agement## Description
closes [#1273](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1273)
closes [#1267](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1267)

feat(individuals): add action list component for individual & merge core into unirefund & navbar improvments

---

apps/web/package.json
apps/web/src/actions/core/AdministrationService/actions.ts
apps/web/src/actions/core/SaasService/actions.ts
apps/web/src/actions/core/SaasService/post-actions.ts
apps/web/src/actions/core/SaasService/put-actions.ts
apps/web/src/actions/unirefund/LocationService/actions.ts
apps/web/src/actions/unirefund/SettingService/actions.ts
apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/[editionId]/move-all-tenants/page.tsx
apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/[editionId]/page.tsx
apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/[tenantId]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/[tenantId]/page.tsx
apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/[tenantId]/set-password/page.tsx
apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/_components/tenants-table-data.tsx
apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/new/page.tsx
apps/web/src/language-data/core/SaasService/resources/en.json
apps/web/src/language-data/core/SaasService/resources/tr.json
pnpm-lock.yaml

refactor(tenants):update  saas to 135 version &  use new system 

---

apps/web/src/language-data/core/SaasService/resources/en.json
apps/web/src/language-data/core/SaasService/resources/tr.json

…d currency labels in English and Turkish language files

chore(tenants): add translation

---

apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/[tenantId]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/new/_components/form.tsx

chore(unirefund): fix some errores

---

apps/web/package.json
apps/web/src/actions/core/AdministrationService/actions.ts
apps/web/src/app/[lang]/(main)/layout.tsx
apps/web/src/lib.ts
apps/web/src/providers/providers.tsx
apps/web/src/providers/tenant.tsx
packages/ui/package.json
packages/utils/auth/auth-actions.ts
pnpm-lock.yaml

closes [#1234](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1234)

feat(tenant-provider): add tenant provider & merge core into unirefund

---

apps/web/package.json
apps/web/src/providers/tenant.tsx
packages/ui/package.json
pnpm-lock.yaml

closes [#1301](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1301)

feat(tenant-provider): add countryCode2 to tenant context and make telephone input use this

---

apps/web/src/app/[lang]/(main)/layout.tsx
apps/web/src/providers/novu.tsx
apps/web/src/providers/providers.tsx
apps/web/src/utils/navbar/notification.tsx

fix(novu): handle missing env variable in Novu components

---

apps/web/src/language-data/unirefund/CRMService/index.ts
apps/web/src/language-data/unirefund/ContractService/index.ts
apps/web/src/language-data/unirefund/ExportValidationService/index.ts
apps/web/src/language-data/unirefund/FinanceService/index.ts
apps/web/src/language-data/unirefund/RefundService/index.ts
apps/web/src/language-data/unirefund/SettingService/index.ts
apps/web/src/language-data/unirefund/TagService/index.ts
apps/web/src/language-data/unirefund/TravellerService/index.ts

feat(language-data): enhance resource data structure for multiple services

---

apps/web/.eslintrc.js
apps/web/get-resources.js
apps/web/package.json
apps/web/src/providers/providers.tsx
packages/ui/.eslintrc.js
packages/ui/package.json
packages/ui/src/components/error-component.tsx
packages/ui/src/components/notification.tsx
packages/ui/src/providers/novu.tsx
packages/ui/src/providers/theme.tsx
packages/ui/src/theme/main-admin-layout/components/navbar.tsx
packages/ui/src/theme/main-admin-layout/index.tsx
packages/ui/src/theme/types/index.tsx
pnpm-lock.yaml

chore:merge core

---

pnpm-lock.yaml

chore: update ayasofyazilim-ui subproject commit reference

---

apps/web/package.json
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/_components/table/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/tag-actions.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/tag-summary.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/page.tsx
apps/web/src/language-data/unirefund/TagService/resources/en.json
apps/web/src/language-data/unirefund/TagService/resources/tr.json
packages/actions/package.json
packages/ui/package.json
pnpm-lock.yaml

…djust pnpm-lock.yaml## Description

feat: allow 'EarlyPaid' status in tag actions visibility logic & update saas

---

packages/actions/core/AccountService/actions.ts
packages/ui/src/theme/main-admin-layout/components/navbar.tsx
pnpm-lock.yaml

chore:merge core to unirefund

---

apps/web/src/app/[lang]/(main)/(core)/settings/tenant/[group]/_components/schema.ts
apps/web/src/app/[lang]/(main)/(core)/settings/tenant/[group]/_components/utils.ts
apps/web/src/app/[lang]/(main)/(core)/settings/tenant/[group]/group.tsx
apps/web/src/app/[lang]/(main)/(core)/settings/tenant/[group]/page.tsx
apps/web/src/app/[lang]/(main)/layout.tsx
apps/web/src/providers/providers.tsx
packages/actions/core/AdministrationService/actions.ts
packages/actions/core/AdministrationService/put-actions.ts
packages/actions/unirefund/AdministrationService/actions.ts
packages/actions/unirefund/AdministrationService/put-actions.ts
packages/actions/unirefund/lib.ts

refactor(CountrySettings): initialize SchemaForm & move unirefund actions related folders

---

apps/web/src/app/[lang]/(main)/(unirefund)/finance/rebate-statements/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/new/_components/form.tsx
packages/ui/src/theme/main-admin-layout/header-section.tsx

feat: update HeaderSection to center align and enlarge page header

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/refunds/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/_components/filter.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/_components/tax-free-tags-search-form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/page.tsx
apps/web/src/app/[lang]/(main)/layout.tsx
apps/web/src/app/[lang]/layout.tsx
apps/web/src/language-data/resources.ts
packages/ui/src/theme/main-admin-layout/components/navbar-searchbar/index.tsx
packages/ui/src/theme/main-admin-layout/components/navbar.tsx
packages/ui/src/theme/main-admin-layout/header-section.tsx

feat(): improve layout and styling of navbar and search components

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/[refundType]/client-page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/_components/summary-section.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/_components/traveller-document-form.tsx

feat: improve layout and spacing in refund operations components

---

apps/web/src/app/[lang]/(main)/layout.tsx
apps/web/src/app/[lang]/layout.tsx
packages/ui/src/theme/main-admin-layout/header-section.tsx

feat: enhance layout with consistent padding in main and header sections

---

apps/web/src/app/[lang]/(main)/(unirefund)/finance/rebate-statements/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/rebate-statements/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/finance/vat-statements/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/export-validations/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/new-tag/page.tsx

**Vat Statements:**
**Rebate Statements:**

feat: add margin and border styling to export validations and new tag pages

---

apps/web/src/app/[lang]/(main)/layout.tsx
apps/web/src/app/[lang]/layout.tsx
packages/ui/src/providers/theme.tsx
packages/ui/src/theme/main-admin-layout/components/navbar-searchbar/index.tsx
packages/ui/src/theme/main-admin-layout/components/navbar.tsx
packages/ui/src/theme/main-admin-layout/header-section.tsx
packages/ui/src/theme/main-admin-layout/index.tsx

<MainAdminLayout componentinin içine parametre olarak ekleniyor

feat(navbar-search): add search from db

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/page.tsx

**Refund Points:**
**Merchants:**

feat: add border and padding styling to merchants and refund points tables

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/layout.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/table.tsx
apps/web/src/app/[lang]/(main)/layout.tsx

feat(parties): Enhance table layouts with consistent styling and padding adjustments

---

apps/web/src/app/[lang]/(main)/(core)/account/layout.tsx
apps/web/src/app/[lang]/(main)/(core)/account/personal-information/_components/personal-information.tsx
apps/web/src/app/[lang]/(main)/(core)/management/identity/organization/organization.tsx
apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/_components/table.tsx
apps/web/src/app/[lang]/(main)/(core)/management/identity/security-logs/_components/table.tsx
apps/web/src/app/[lang]/(main)/(core)/management/identity/users/_components/table.tsx
apps/web/src/app/[lang]/(main)/(core)/management/language-management/language-texts/_components/table.tsx
apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/_components/table.tsx
apps/web/src/app/[lang]/(main)/(core)/management/logs/layout.tsx
apps/web/src/app/[lang]/(main)/(core)/management/text-templates/_components/table.tsx

feat(management): Add consistent padding and border styling to table components

---

apps/web/.env.example
apps/web/src/app/[lang]/(main)/(unirefund)/home/dashboard.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/home/page.tsx
turbo.json

feat: add support for Superset URL and Dashboard ID in environment and dashboard components

---

.github/workflows/publish.yml

fix: correct indentation for app input in publish.yml

---

apps/ssr/src/app/[lang]/(auth)/login/page.tsx
apps/ssr/src/app/[lang]/(auth)/register/page.tsx
apps/ssr/src/app/[lang]/(auth)/reset-password/page.tsx
apps/ssr/src/app/[lang]/(main)/(protected)/layout.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/header.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/scan-button.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/scan-password.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/tax-form-input.tsx
apps/ssr/src/app/[lang]/(main)/(public)/home/client.tsx
apps/ssr/src/app/[lang]/(main)/(public)/home/page.tsx
apps/ssr/src/app/[lang]/(main)/(public)/layout.tsx
apps/ssr/src/app/[lang]/(main)/(public)/searchTransaction/client.tsx
apps/ssr/src/app/[lang]/(main)/(public)/searchTransaction/page.tsx

feat: implement client-side components for scanning and transaction management

---

apps/ssr/public/idcard-mrz.svg
apps/ssr/public/passport-mrz.svg
apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps/scan-document.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/webcam.tsx
apps/ssr/src/app/[lang]/(main)/(public)/home/page.tsx
apps/ssr/src/app/[lang]/(main)/(public)/layout.tsx
apps/ssr/src/app/[lang]/layout.tsx

feat: new ios style webcam component,layout changes

---

apps/ssr/src/app/[lang]/(main)/(public)/layout.tsx
apps/ssr/src/app/[lang]/layout.tsx

fix: update layout height class to use dynamic viewport height

---

apps/ssr/src/app/[lang]/(main)/(public)/_components/actions.ts
apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps/scan-document.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps/start.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/webcam.tsx
apps/ssr/src/app/[lang]/(main)/(public)/home/page.tsx

fix: adjust layout and improve webcam component styling

---

apps/ssr/package.json
apps/ssr/src/app/[lang]/(main)/(public)/_components/liveness-detector.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps/liveness-dedection.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps/scan-document.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps/take-selfie.tsx
apps/ssr/src/app/globals.css
packages/actions/package.json
packages/actions/unirefund/AWSService/actions.ts
pnpm-lock.yaml

refacor: code structure for improved readability and maintainability,feat:aws liveness-detector

---

apps/web/src/app/[lang]/(main)/(core)/management/file/_components/utils.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/file-relation-entities/[fileRelationEntityId]/_components/form-edit.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/file-relation-entities/[fileRelationEntityId]/_components/form-new.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/file-relation-entities/[fileRelationEntityId]/page.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/file-type-mime-types/_components/file-type-mime-type-table-data.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/file-type-mime-types/_components/table.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/file-type-mime-types/page.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/file-types/[fileTypeId]/_components/form-edit.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/file-types/[fileTypeId]/_components/form-new.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/file-types/[fileTypeId]/page.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/list/page.tsx
apps/web/src/language-data/core/AbpUiNavigation/resources/en.json
apps/web/src/language-data/core/AbpUiNavigation/resources/tr.json
apps/web/src/language-data/unirefund/FileService/index.ts
apps/web/src/language-data/unirefund/FileService/resources/en.json
apps/web/src/language-data/unirefund/FileService/resources/tr.json
apps/web/src/utils/navbar/project-navbar-items.json
packages/ui/src/form-ready/index.tsx
packages/ui/src/theme/main-admin-layout/components/navbar.tsx

feat(FileService): check form ready states for better user experience

---

apps/ssr/src/app/[lang]/(main)/(public)/_components/liveness-detector.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps.tsx
apps/ssr/src/language-data/unirefund/SSRService/resources/en.json
apps/ssr/src/language-data/unirefund/SSRService/resources/tr.json
packages/actions/unirefund/AWSService/actions.ts

feat: Integrate face comparison functionality and update API endpoints for liveness session

---

apps/ssr/package.json
apps/ssr/src/app/[lang]/(main)/(public)/_components/header.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/liveness-detector.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps.tsx
apps/ssr/src/app/[lang]/(main)/(public)/layout.tsx
apps/ssr/src/language-data/resources.ts
apps/web/package.json
packages/actions/package.json
packages/actions/unirefund/AWSService/actions.ts
packages/actions/unirefund/TravellerService/actions.ts
packages/actions/unirefund/TravellerService/post-actions.ts
packages/ui/src/theme/main-admin-layout/components/language-selector/index.tsx
pnpm-lock.yaml

Refactor code structure for improved readability and maintainability

---

apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps/scan-document.tsx

refactor: Improve code formatting and enhance readability in scan-document and start components

---

apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps/_components/document-onboarding.tsx

refactor: Improve code formatting and consistency in validation steps components

---

apps/ssr/src/app/[lang]/(auth)/layout.tsx
apps/ssr/src/app/[lang]/(auth)/register/page.tsx
apps/ssr/src/app/[lang]/(auth)/reset-password/page.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps.tsx
apps/ssr/src/app/[lang]/(main)/(public)/_components/validation-steps/start.tsx
apps/ssr/src/language-data/unirefund/SSRService/resources/en.json
apps/ssr/src/language-data/unirefund/SSRService/resources/tr.json

feat: Enhance authentication layout with logo and language selector update register and reset password pages for improved structure and functionality

feat: Auth design has been improved. Reset password page has been activated. SSR Steps web view has been edited.

---

apps/ssr/package.json
apps/web/package.json
apps/web/src/app/[lang]/(main)/(core)/management/file/file-types/[fileTypeId]/_components/form-edit.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/[contractId]/stores/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/[id]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/page.tsx
apps/web/src/language-data/resources.ts
packages/actions/package.json
packages/actions/unirefund/FileService/put-actions.ts
pnpm-lock.yaml

feat:update file service saas

---

apps/web/src/app/[lang]/(main)/(core)/management/file/_components/utils.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/verification/[fileId]/_components/data.json
apps/web/src/app/[lang]/(main)/(core)/management/file/verification/[fileId]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/verification/[fileId]/_components/schema.json
apps/web/src/app/[lang]/(main)/(core)/management/file/verification/[fileId]/page.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/verification/_components/table.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/verification/page.tsx
apps/web/src/app/[lang]/(main)/layout.tsx
apps/web/src/language-data/unirefund/FileService/resources/en.json
apps/web/src/language-data/unirefund/FileService/resources/tr.json
packages/ui/src/theme/main-admin-layout/components/language-selector/index.tsx

feat:initialize file verification pages

---

apps/ssr/package.json
apps/web/package.json
packages/actions/package.json
pnpm-lock.yaml

chore: update @ayasofyazilim/saas dependency to version 0.0.151

---

apps/web/src/language-data/unirefund/FileService/resources/en.json
apps/web/src/language-data/unirefund/FileService/resources/tr.json
packages/ui/src/unirefund/file-upload/_components/container.tsx
packages/ui/src/unirefund/file-upload/_components/file-upload-base.tsx
packages/ui/src/unirefund/file-upload/_components/form.tsx
packages/ui/src/unirefund/file-upload/index.tsx

fix: handle empty form data in onChange event

---

apps/web/src/app/[lang]/(main)/(core)/management/file/verification/[fileId]/layout.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/verification/[fileId]/verify/_components/form-header.tsx
apps/web/src/app/[lang]/(main)/(core)/management/file/verification/[fileId]/verify/_components/form.tsx

feat: add disabled state to actions and form components for better user experience

---

apps/ssr/package.json
apps/web/package.json
packages/actions/package.json
pnpm-lock.yaml

chore: update next.js version to 14.2.29 across all packages

---

apps/ssr/package.json
apps/web/package.json
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/new/components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/contracts/[contractId]/contract/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/contracts/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/new/_components/form.tsx
packages/actions/package.json
packages/ui/package.json
pnpm-lock.yaml

chore: update @ayasofyazilim/saas version to 0.0.155 across all packages and remove earlyRefund field from forms

---

apps/web/src/language-data/resources.ts

feat:update submodule & resources 

---

packages/ui/src/unirefund/file-upload/_components/form.tsx

fix: move onChange to onSubmit for temporary fix i will investigate this issue later

---

apps/ssr/package.json
apps/web/package.json
packages/actions/package.json
packages/ui/package.json
pnpm-lock.yaml

chore: update saas

---

package.json

 feat: update saas and saas-dev scripts to include ui package filter 

---

apps/ssr/package.json
apps/ssr/src/app/[lang]/(main)/(public)/evidence/page.tsx
apps/ssr/src/components/validation-steps.tsx
apps/ssr/src/components/validation-steps/scan-document.tsx
packages/actions/package.json
packages/ui/package.json
pnpm-lock.yaml

feat: add session handling to ScanDocument component and integrate MRZ analysis API

---

apps/ssr/src/app/[lang]/(main)/(public)/layout.tsx
apps/ssr/src/app/[lang]/(main)/(public)/page.tsx

chore: add landing page with no sense

---

apps/web/src/app/[lang]/(main)/(unirefund)/home/analytics/client.tsx
packages/ui/src/dashboard-layout/index.tsx
packages/ui/src/sortable-layout/sortable-item.tsx
pnpm-lock.yaml

feat:update ui

---

.gitignore
apps/ssr/src/components/liveness-detector.tsx
apps/ssr/src/components/validation-steps.tsx
packages/actions/unirefund/TravellerService/actions.ts

feat: liveness api integration

---

packages/ui/src/theme/main-admin-layout/components/language-selector/index.tsx

feat: add showFlag prop to LanguageSelector for conditional flag display

---

.github/workflows/deploy.yml
deploy.sh

feat:add new deployment

---

deploy.sh

chore:update deploy.sh

---

.github/workflows/deploy.yml

feat:new deploy action

---

.github/workflows/deploy.yml

chore:update deploy.yml

---

.github/workflows/deploy.yml

chore:update deployment

---

.github/workflows/deploy.yml

chore:final deployment

---

.github/workflows/lint-pull-requests.yml
apps/ssr/src/app/[lang]/(main)/(public)/landing/page.tsx
apps/ssr/src/language-data/resources.ts
packages/ui/src/components/address/address.tsx
packages/ui/src/components/address/field.tsx
packages/ui/src/form-ready/index.tsx
packages/ui/src/toast-on-submit/index.tsx
pnpm-lock.yaml

feat: ssr & new form ready 

---

apps/ssr/src/language-data/resources.ts
packages/ui/src/theme/main-admin-layout/components/language-selector/index.tsx

fix: update language selector to use conditional rendering for flags

---

apps/ssr/src/app/[lang]/(auth)/evidence/login/client.tsx
apps/ssr/src/app/[lang]/(auth)/evidence/login/page.tsx
apps/ssr/src/app/[lang]/(auth)/evidence/register/client.tsx
apps/ssr/src/app/[lang]/(auth)/evidence/register/page.tsx
apps/ssr/src/app/[lang]/(auth)/evidence/reset-password/client.tsx
apps/ssr/src/app/[lang]/(auth)/evidence/reset-password/page.tsx
apps/ssr/src/app/[lang]/(auth)/layout.tsx
apps/ssr/src/app/[lang]/(main)/(protected)/_components/header.tsx
apps/ssr/src/app/[lang]/(main)/(public)/landing/page.tsx
apps/ssr/src/components/validation-steps.tsx

feat: update header link to direct to home and add session authentication with redirect

---

.github/workflows/create-tag.yml
.github/workflows/deploy.yml

chore:Update deploy yml 

---

.github/workflows/create-tag.yml

chore:trigger yml

---

.github/workflows/auto-deploy.yml

chore:auto-deploy

---

.github/workflows/auto-deploy.yml
.github/workflows/deploy.yml

feat:update manual deployment

---

.github/workflows/auto-deploy.yml

 chore:update auto-yaml 

---

.github/workflows/create-tag.yml
.github/workflows/deploy.yml
.github/workflows/lint-pull-requests.yml

chore:update github actions for single branch method

---

.github/workflows/deploy.yml

chore:remove release on deploy

---

.github/workflows/auto-deploy.yml
.github/workflows/deploy.yml

feat:new deploy & tag management

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/new/_components/form.tsx

closes [#1379](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1379)

fix(Style): tables in schema form had invalid classNames

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/invoices.tsx

chore:update invoice line product group list

---

apps/ssr/src/app/[lang]/(main)/(protected)/(other)/layout.tsx
apps/ssr/src/app/[lang]/(main)/(protected)/_components/chatwoot.tsx

chore:update chatwoot for sending user details

---

apps/ssr/src/app/[lang]/(main)/(protected)/_components/chatwoot.tsx

chore: add chatwoot:ready listener

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/_components/contact/address-form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/[partyId]/details/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/individuals/[partyId]/details/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/details/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/[partyId]/details/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/[partyId]/details/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/[partyId]/details/page.tsx
packages/saas/CRMService/schemas.gen.ts
packages/saas/CRMService/sdk.gen.ts
packages/saas/CRMService/types.gen.ts

feat:update and create party address

---

packages/actions/unirefund/lib.ts
packages/saas/new.mjs
packages/saas/package.json
pnpm-lock.yaml

 feat:initialize new saas generator

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/_components/contact/address-form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/_components/contact/email-form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/_components/contact/phone-form.tsx
apps/web/src/language-data/resources.ts

 fix:update traveller page on server response 

---

apps/web/tests/unirefund/parties/refund-points/new/create.refund.points.spec.ts

test: create new refund points test

---

apps/web/tests/unirefund/parties/customs/new/create.customs.spec.ts

test: create new customs test

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/new-tag/_components/product-group-amount-input.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/new-tag/client.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/page.tsx
packages/saas/TagService/schemas.gen.ts
packages/saas/TagService/sdk.gen.ts
packages/saas/TagService/types.gen.ts

fix(Tag): update tag service

---

apps/web/package.json
apps/web/src/language-data/resources.ts
apps/web/src/providers/locale.tsx
pnpm-lock.yaml

closes [#624](https://github.com/ayasofyazilim-clomerce/unirefund-web/issues/624)

fix:date input culture

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/new-tag/client.tsx

fix:new tag send external store identifier

---

apps/web/tests/unirefund/_support/expect-toast.ts
apps/web/tests/unirefund/parties/merchants/merchants-edit/edit.merchant.spec.ts

feat: add tests for merchant edit functionality with randomized inputs

---

apps/web/src/app/[lang]/(main)/layout.tsx
apps/web/src/utils/affiliation-switch/index.tsx
apps/web/src/utils/types.d.ts

feat:update aff switch

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/new-tag/client.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/invoices.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/page.tsx

closes [#638](https://github.com/ayasofyazilim-clomerce/unirefund-web/issues/638)

chore: update tag detail

---

apps/web/src/utils/navbar/project-navbar-items.json

closes [#642](https://github.com/ayasofyazilim-clomerce/unirefund-web/issues/642)

fix: finance services navbar menus

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/_components/affiliations/drawer/index.tsx

closes [#1141](https://github.com/ayasofyazilim-clomerce/UniRefund/issues/1141)

style: increase max width of drawer components for better layout

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/refund/_components/traveller-document-form.tsx

closes [#648](https://github.com/ayasofyazilim-clomerce/unirefund-web/issues/648)

fix: get refundpoint from claim

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/product-groups/product-group-table-data.tsx

fix: reorder imports and enhance product group creation dialog handling

---

apps/web/package.json
apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/[tenantId]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/[tenantId]/page.tsx
apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/new/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/page.tsx
apps/web/src/providers/tenant.tsx
packages/ui/src/components/address/address-combobox.tsx
pnpm-lock.yaml

fix: Remove unused timezoneList and clean up

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/new/_components/form.tsx

chore: update spacing

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/new-tag/client.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/customs/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/refund-points/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-free/_components/table-data.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/tax-offices/_components/table-data.tsx
apps/web/src/language-data/resources.ts
apps/web/src/utils/affiliation-switch/index.tsx
packages/saas/CRMService/schemas.gen.ts
packages/saas/CRMService/sdk.gen.ts
packages/saas/CRMService/types.gen.ts
packages/saas/TagService/schemas.gen.ts
packages/saas/TagService/sdk.gen.ts
packages/saas/TagService/types.gen.ts

fix: rename externalStoreIdentifier to externalIdentifier across multiple files and update related types and schemas

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/_components/individual-form.tsx
packages/ui/src/theme/main-admin-layout/components/breadcrumb/index.tsx

chore: remove addres field on individual create form

---

packages/saas/CRMService/schemas.gen.ts
packages/saas/CRMService/types.gen.ts
packages/saas/ContractService/schemas.gen.ts
packages/saas/ContractService/sdk.gen.ts
packages/saas/ContractService/types.gen.ts
packages/saas/ExportValidationService/sdk.gen.ts
packages/saas/FileService/FileServiceClient.ts
packages/saas/FileService/schemas.gen.ts
packages/saas/FileService/sdk.gen.ts
packages/saas/FileService/types.gen.ts
packages/saas/LocationService/sdk.gen.ts
packages/saas/RefundService/schemas.gen.ts
packages/saas/RefundService/types.gen.ts
packages/saas/TagService/schemas.gen.ts
packages/saas/TagService/sdk.gen.ts
packages/saas/TagService/types.gen.ts
packages/saas/TravellerService/schemas.gen.ts
packages/saas/TravellerService/types.gen.ts

saas: update saas

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/_components/invoices.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/tax-free-tags/[tagId]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/_components/affiliations/drawer/step-1.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/rebate-tables/_components/schema.ts
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/_components/schema.ts
apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-tables/_components/schema.ts

fix: type errors

---

apps/web/src/app/[lang]/(main)/(unirefund)/operations/export-validations/[exportValidationId]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/export-validations/[exportValidationId]/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/operations/export-validations/[exportValidationId]/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/[contractId]/contract/_components/form.tsx

feat: enhance form components with default values and improved UI schema for export validations

---

packages/ui/src/theme/main-admin-layout/components/navbar-searchbar/index.tsx

refactor: improve code formatting and structure in SearchBar component

---

apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/[contractId]/rebate-settings/_components/rebate-settings.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/[contractId]/stores/_components/table.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/[contractId]/stores/page.tsx
apps/web/src/app/[lang]/(main)/(unirefund)/parties/merchants/[partyId]/contracts/_components/utils.tsx
apps/web/src/language-data/unirefund/ContractService/resources/en.json
apps/web/src/language-data/unirefund/ContractService/resources/tr.json

feat:add formReady component to contract sub details

---

apps/web/src/app/[lang]/(main)/(unirefund)/settings/templates/refund-fees/new/_components/form.tsx

fix: adjust column spans for responsive layout in RefundFeeHeaderForm

---

apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/_components/languages-table-data.tsx

fix: improve import formatting and enhance column visibility in languages table
